import WeightedGraph from './lib/weighted-graph.class.js'

const wg = new WeightedGraph()

wg.addEdge('Igarapava', 'Rifaina', 47)
wg.addEdge('Igarapava', 'Jeriquara', 41)
wg.addEdge('Igarapava', 'Ituverava', 37)
wg.addEdge('Ituverava', 'Guará', 14)
wg.addEdge('Guará', 'São Joaquim da Barra', 21)
wg.addEdge('Guará', 'Ribeirão Corrente', 25)
wg.addEdge('Jeriquara', 'Ribeirão Corrente', 26)
wg.addEdge('Jeriquara', 'Pedregulho', 15)
wg.addEdge('Jeriquara', 'Cristais Paulista', 25)
wg.addEdge('Rifaina', 'Pedregulho', 28)
wg.addEdge('Pedregulho', 'Cristais Paulista', 23)
wg.addEdge('Ribeirão Corrente', 'Franca', 34)
wg.addEdge('Ribeirão Corrente', 'Franca', 27)
wg.addEdge('Cristais Paulista', 'Franca', 21)
wg.addEdge('São Joaquim da Barra', 'São José da Bela Vista', 37)
wg.addEdge('São José da Bela Vista', 'Franca', 33)
wg.addEdge('Franca', 'Ibiraci', 39)
wg.addEdge('Franca', 'Claraval', 24)
wg.addEdge('Ibiraci', 'Claraval', 25)
wg.addEdge('Franca', 'Patrocínio Paulista', 19)
wg.addEdge('Patrocínio Paulista', 'Itirapuã', 9)
wg.addEdge('Franca', 'Restinga', 15)
wg.addEdge('Franca', 'Batatais', 50)
wg.addEdge('Restinga', 'Batatais', 40)
wg.addEdge('Batatais', 'Patrocínio Paulista', 64)

console.log(wg.shortestDistance('Restinga'))
